services:
  - type: web
    name: discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: ALERT_CHANNEL_ID
        sync: false